[package]
name = "insufficient_encapsulation"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.8.0", features = ["v4", "serde"] }
